name: "Workflow Dispatch"
on: push
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  call-lint:
    name: "Lint"
    uses: ./.github/workflows/lint.yml

  call-build:
    name: "Build & Test"
    needs: call-lint
    uses: ./.github/workflows/build.yml
